### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by amckinstry** [sentinel-hub/EOBrowser#1]
Hi,
Its not clear what the copyright / licensing for this software is. Is this open source, and if so, which license ? 
I would like to package this software for Debian Linux.
Best regards
Alastair McKinstry

**Comment by sinergise-anze** [comment]
Hi,

sorry for late reply, we were not notified about the issue raised. The license is MIT ("Expat"), we will update the repository accordingly soon. I'll leave this issue open until this is done.

Thanks for bringing this to our attention.

Kind regards,

Anze @ Sinergise

**Comment by sinergise-anze** [comment]
Added `LICENSE.md`.

**Comment by amckinstry** [comment]
Thank you for this.
