### ISSUE TITLE
All Landsat doesn't work in compare option

### ISSUE THREAD

**Issue by Digdgeo** [sentinel-hub/EOBrowser#14]
Hi, just to let you know that Landsat 5 doesn't appear in the Compare option. They seems to be there, but you can't see them in the comparation.

**Comment by zcernigoj** [comment]
Hey,

I suggest that you create a post on the [forum](https://forum.sentinel-hub.com/) in the future as there is a better chance for the answer there.

But to tackle the issue, I checked in Chrome and Firefox and it seems to work for me. Can you provide more info? Maybe the date on which the Landsat 5 data is not available was selected.

This is how it looks for me:

- The order of the layers in the **Compare** tab:
![image](https://user-images.githubusercontent.com/54022976/116371341-9900b880-a80b-11eb-9dde-644c5569f93c.png)

- The visualization of the compared layers:
![image](https://user-images.githubusercontent.com/54022976/116371253-85555200-a80b-11eb-8733-7dd7a8b1445f.png)

Cheers.

**Comment by zcernigoj** [comment]
Closing the issue. Reopen (with added information) if it occurs again.
