### ISSUE TITLE
TCI - Saturation level

### ISSUE THREAD

**Issue by DDRASL** [sentinel-hub/EOBrowser#9]
Hello,

I noticed a difference between the True Color image that I can see in your EOBrowser versus the TCI file that I download from Copernicus Open Access Hub, for Sentinel-2 products (example below is for 2A).
For instance, if we take a look at Madrid's airport with a Sentinel-2 L2A True Color image taken on January 4, 2020:
 - From your EOBrowser, I see this : 
![image](https://user-images.githubusercontent.com/63846810/79555057-442a4e00-809f-11ea-931f-f6b28772b1bd.png)
(link: https://apps.sentinel-hub.com/eo-browser/?lat=40.48534&lng=-3.56283&zoom=14&time=2020-01-04&preset=1_TRUE_COLOR&datasource=Sentinel-2%20L2A; version: v2.20.24)
 - From Copernicus Open Access Hub, the TCI file looks like this:
![image](https://user-images.githubusercontent.com/63846810/79554609-9880fe00-809e-11ea-98f0-afa5016b7ff7.png)
(product id: 93043770-c395-4308-ad51-b1b8b7673678; product title: S2A_MSIL2A_20200104T110441_N0213_R094_T30TVK_20200104T122020; download link: https://scihub.copernicus.eu/dhus/odata/v1/Products('93043770-c395-4308-ad51-b1b8b7673678')/$value)

A striking difference between the two images is the difference in saturation level.
Notice, for instance, how the bottom part of the TCI image from Copernicus OAH is much brighter than on the EOBrowser.

Hence, the question is twofold: Do you apply another post-processing step on TCI image from ESA ? If yes, can you provide more details about this post-processing step?

Thank for your support

**Comment by sinergise-anze** [comment]
If you check the web browser console ("Network" tab), you should be able to inspect the scripts that we are using to render the images for this layer. 

In this case the `evalscript` parameter is:
```
//VERSION=3
let minVal = 0.0;
let maxVal = 0.4;

let viz = new HighlightCompressVisualizer(minVal, maxVal);

function setup() {
   return {
    input: ["B04", "B03", "B02","dataMask"],
    output: { bands: 4 }
  };
}

function evaluatePixel(samples) {
    let val = [samples.B04, samples.B03, samples.B02,samples.dataMask];
    return viz.processList(val);
}
```

You can find more information about HighlightCompressVisualizer [here](https://www.sentinel-hub.com/faq/which-functions-can-be-used-custom-script) and [here](https://www.sentinel-hub.com/faq/how-configure-visualization-so-it-reflects-old-styles).

However this is not really an issue about EO browser itself, it has more to do with [Sentinel Hub](https://www.sentinel-hub.com/). If you need a more detailed answer, I would kindly ask you to post this question to our [forum](https://forum.sentinel-hub.com/) where it will benefit a wider community (you are also more likely to get a better answer there). Thank you!
